### ISSUE TITLE
Craft 3 DB Backups Failing

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/nitro#139]
Re this closed issue: https://github.com/craftcms/cms/issues/2364

When transitioning to Nitro (default install), the above mentioned issue arose for the first time.
The referenced closed issue is about Mamp, but I guess the problem is the same here.

Looks like Craft/PHP can't find the mysqldump executable.

Here's the error log:
```
2020-05-13 20:29:37 [-][1][-][error][yii\base\Exception] yii\base\Exception: Could not create backup: The shell command "mysqldump --defaults-extra-file="/nitro/sites/vlp.test/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --single-transaction --no-data --result-file="/nitro/sites/vlp.test/storage/backups/i-flash_200513_182937_vdcfidbbsh_v3.5.0-beta.2.sql" vlp && mysqldump --defaults-extra-file="/nitro/sites/vlp.test/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-create-info --ignore-table=vlp.craft_assetindexdata --ignore-table=vlp.craft_assettransformindex --ignore-table=vlp.craft_sessions --ignore-table=vlp.craft_templatecaches --ignore-table=vlp.craft_templatecachequeries --ignore-table=vlp.craft_templatecacheelements --ignore-table=vlp.craft_cache --ignore-table=vlp.craft_templatecachecriteria vlp >> "/nitro/sites/vlp.test/storage/backups/i-flash_200513_182937_vdcfidbbsh_v3.5.0-beta.2.sql"" failed with exit code 127: sh: 1: mysqldump: not found in /nitro/sites/vlp.test/vendor/craftcms/cms/src/controllers/UtilitiesController.php:334
Stack trace:
#0 [internal function]: craft\controllers\UtilitiesController->actionDbBackupPerformAction()
#1 /nitro/sites/vlp.test/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#2 /nitro/sites/vlp.test/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#3 /nitro/sites/vlp.test/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#4 /nitro/sites/vlp.test/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#5 /nitro/sites/vlp.test/vendor/craftcms/cms/src/web/Application.php(289): yii\base\Module->runAction()
#6 /nitro/sites/vlp.test/vendor/craftcms/cms/src/web/Application.php(557): craft\web\Application->runAction()
#7 /nitro/sites/vlp.test/vendor/craftcms/cms/src/web/Application.php(268): craft\web\Application->_processActionRequest()
#8 /nitro/sites/vlp.test/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#9 /nitro/sites/vlp.test/web/index.php(21): yii\base\Application->run()
#10 {main}
```

Nitro version is beta 2.
Craft is 3.5 beta 2, but the same error occurs on the latest 3.4.

**Comment by angrybrad** [comment]
This will resolve itself once https://github.com/craftcms/nitro/issues/54 is implemented.

**Comment by jasonmccallister** [comment]
@JeanLucEsser this should be resolved in the latest version (beta 6).
