### ISSUE TITLE
Failed to open redis DB connection

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/nitro#187]
### Description

```
yii\db\Exception: Failed to open redis DB connection (tcp://craft-redis:6379, database=0): 0 - php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2-redis/src/Connection.php:643
Stack trace:
#0 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2-redis/src/Connection.php(744): yii\redis\Connection->open()
#1 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2-redis/src/Cache.php(248): yii\redis\Connection->executeCommand()
#2 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/caching/Cache.php(255): yii\redis\Cache->setValue()
#3 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/controllers/TemplatesController.php(183): yii\caching\Cache->set()
#4 [internal function]: craft\controllers\TemplatesController->actionRequirementsCheck()
#5 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#6 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#7 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#8 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#9 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction()
#10 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/controllers/InstallController.php(67): craft\web\Application->runAction()
#11 [internal function]: craft\controllers\InstallController->actionIndex()
#12 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#13 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#14 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#15 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#16 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction()
#17 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/web/Application.php(513): craft\web\Application->runAction()
#18 /home/ubuntu/sites/funko-craftcms-nitro/vendor/craftcms/cms/src/web/Application.php(186): craft\web\Application->_processInstallRequest()
#19 /home/ubuntu/sites/funko-craftcms-nitro/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#20 /home/ubuntu/sites/funko-craftcms-nitro/web/index.php(21): yii\base\Application->run()
#21 {main}
Additional Information:
php_network_getaddresses: getaddrinfo failed: Name or service not known
```

### Steps to reproduce

I just got finished importing the db and adding my code to Nitro ... I'm sure I'm missing something easy here, but I'm getting this error when visiting the admin.

### Additional info

- Nitro version: 1.0.0-beta.10
- Multipass version: 1.3.0+mac

**Comment by jasonmccallister** [comment]
@ryanpcmcquen it looks likes its trying to connect to the hostname `craft-redis`. That should be using `127.0.0.1`.

**Comment by ryanpcmcquen** [comment]
@jasonmccallister, you are 100% correct, that was my config issue. Nothing to see here.

![external-content duckduckgo com](https://user-images.githubusercontent.com/772937/88209739-04c44e00-cc08-11ea-889d-a7fb04c70f9a.gif)
