### ISSUE TITLE
Support for vite configuration

### ISSUE THREAD

**Issue by rellafella** [craftcms/nitro#360]
### Description
Working through [Andrew Welsh's article](https://nystudio107.com/blog/using-vite-js-next-generation-frontend-tooling-with-craft-cms) about using Vite for local dev with Craft. I feel like this config is very close to working but have run into a CORS issue, but can't seem to figure out why.

There is a heap of information here, but please let me know if I have missed anything that you might need to reproduce.

<img width="1013" alt="Screen Shot 2021-05-21 at 10 53 12 pm" src="https://user-images.githubusercontent.com/36829732/119144071-76b72f00-ba87-11eb-9ccd-1363c7a24b3a.png">

#### vite.config.js
```js
import vue from '@vitejs/plugin-vue';
import ViteRestart from 'vite-plugin-restart';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import path from 'path';

// https://vitejs.dev/config/
export default ({ command }) => ({
  base: command === 'serve' ? '' : '/dist/',
  build: {
    manifest: true,
    outDir: './web/dist',
    rollupOptions: {
      input: {
        app: './src/js/app.js'
      },
      output: {
        sourcemap: true
      }
    }
  },
  plugins: [
    nodeResolve({
      moduleDirectories: [path.resolve('./node_modules')]
    }),
    ViteRestart({
      reload: ['./templates/**/*']
    }),
    vue()
  ],
  publicDir: './src/public',
  resolve: {
    alias: {
      '@': '/src'
    }
  },
  server: {
    host: '0.0.0.0'
  }
});

```

#### vite.php
```php
<?php

use craft\helpers\App;

return [
    'useDevServer' => App::env('DEV_MODE'),

    'manifestPath' => '@webroot/dist/manifest.json',

    'devServerPublic' => App::env('VITE_DEV_SERVER_PUBLIC'),

    'serverPublic' => App::env('SITE_URL') . '/dist/',

    'errorEntry' => '/src/js/app.js',

    'cacheKeySuffix' => '',

    'devServerInternal' => App::env('VITE_DEV_SERVER_PUBLIC'),

    'checkDevServer' => true,
];
```

#### package.json
```json
{
  "scripts": {
    "dev": "vite",
    "build": "vite build"
  },
  "dependencies": {
    "vue": "^3.0.5",
    "vue-confetti": "^2.0.8"
  },
  "devDependencies": {
    "@rollup/plugin-node-resolve": "^13.0.0",
    "@vitejs/plugin-vue": "^1.2.2",
    "@vue/compiler-sfc": "^3.0.5",
    "autoprefixer": "^10.2.5",
    "postcss": "^8.2.12",
    "tailwindcss": "^2.1.2",
    "vite": "^2.3.2",
    "vite-plugin-restart": "0.0.2"
  }
}
```
#### relevent env vars
```
DEV_MODE=1
SITE_URL=http://liamrella.test
VITE_DEV_SERVER_PUBLIC=http://localhost:3000/
WEB_ROOT_PATH=/app/web (aliased as @webroot)
```

### Steps to reproduce

1. ssh into Nitro site container
2. run npm run dev

### Additional info

- Nitro CLI: 	 2.0.8
- Nitro gRPC: 	 2.0.8
- Docker API: 	 1.41 (1.12 min)
- Docker CLI: 	 1.41
- Craft CMS:     3.6.15
- Vite (Craft plugin): 1.0.5

**Comment by jasonmccallister** [comment]
@rellafella when you access the site directly, can you inspect the headers in the network tab and provide the output?

**Comment by khalwat** [comment]
Maybe you'll find some hints here? https://nystudio107.com/docs/vite/#local-development-environment-setup

As for CORS, Vite by default:

https://vitejs.dev/config/#server-cors

Sets it up to allow access from any origin. So your error is a little puzzling.

**Comment by rellafella** [comment]
> @rellafella when you access the site directly, can you inspect the headers in the network tab and provide the output?

#### Response headers (app.js)
HTTP/1.1 200 OK
Server: Caddy
Date: Fri, 21 May 2021 21:33:15 GMT
Content-Length: 0

> As for CORS, Vite by default:
> 
> https://vitejs.dev/config/#server-cors
> 
> Sets it up to allow access from any origin. So your error is a little puzzling.

This is what has me puzzled too, I have tried playing around with the server.cors options too with no luck. 

> This really shouldn't be any different than setup for `webpack` or Laravel `mix` or the like, so maybe this article will help out: https://andrewmeni.ch/blog/hot-module-reloading-with-laravel-mix-v6-and-craft-nitro-2

I'll see how I go trying to incorporate Andrew Menich's dev server config from mix and let you know on here if there is anything different.

**Comment by rellafella** [comment]
Update:
I got this setup with mix 6 as per Andrew Menich's article without any CORS errors. Can't  seem to see any discernible difference between the configurations, apart from the obvious. 

That was following almost an identical configuration, obviously leveraging Twigpack instead though. But still the same process of `nitro ssh` then `npm run dev` in there. Files were being served from http://loclahost:3000

So still a bit perplexed. I am getting many more headers from the webpackDevserver files compared to the Vite dev server. 
#### Response headers (app.js)
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Authorization
Access-Control-Allow-Methods: GET, HEAD, OPTIONS
Access-Control-Allow-Origin: *
Content-Encoding: gzip
Content-Type: application/javascript; charset=utf-8
Date: Sun, 23 May 2021 13:29:58 GMT
Etag: W/"109df7-nygZAVBgQ9ovmqYIQZEV2Bsx2nI"
Server: Caddy
Vary: Accept-Encoding
X-Powered-By: Express
Transfer-Encoding: chunked
```

**Comment by khalwat** [comment]
I think Vite might use a web socket for some of this -- not sure how that'd impact anything tho.

**Comment by rellafella** [comment]
I am not really sure what to do with this information but it might be useful to the issue.

In Andrew M's article he recommends using curl to debug the location of the webpack manifest so out of interest I thought I would try a similar thing with Vite.

If I run `curl -I 'http://localhost:3000/src/js/app.js'` I am getting a bunch of headers that are not present in the browser. Including `Access-Control-Allow-Origin: *`

```sh
/app $ curl -I 'http://localhost:3000/src/js/app.js'
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/javascript
Content-Length: 351
Last-Modified: Mon, 24 May 2021 02:23:33 GMT
ETag: W/"351-1621823013222"
Cache-Control: no-cache
Date: Mon, 24 May 2021 02:36:43 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

**Comment by khalwat** [comment]
@rellafella set:

```php
    'checkDevServer' => false,
```

I'm pretty sure that what's happening is since you have that on, it's testing:

```php
    'devServerInternal' => App::env('VITE_DEV_SERVER_PUBLIC'),
```

...to see if the Vite dev server is running. Since you have it set to:

```
VITE_DEV_SERVER_PUBLIC=http://localhost:3000/
```

...this is going to fail, because it's doing this _inside_ of the Docker network. The address in there _will not be_ the same as the `VITE_DEV_SERVER_PUBLIC` address. It'll be an internal Docker networking address.

So turn off `checkDevServer` until you're able to determine the internal Nitro network address for `devServerInternal`

For my Docker setup for example, it looks like this:

```
# Vite settings
VITE_DEV_SERVER_PUBLIC=http://localhost:3000/
VITE_DEV_SERVER_INTERNAL=http://vite:3000/
```

**Comment by rellafella** [comment]
Have tried toggling `checkDevServer` but it doesn't seem to have any effect.

**Comment by khalwat** [comment]
It definitely will have an effect... if you tell it to check for the dev server, and it can't connect to it, it will fall back on the production build.

**Comment by rellafella** [comment]
Sorry, yes in that respect it does have an effect, but it doesn't seem to change anything for the CORS issue.

I have tried a few different values for `devServerInternal` but it seems as though "http://localhost:3000" is the only one that will resolve if I try pinging it while the dev server is running.

**Comment by andrewmenich** [comment]
I've been summoned!

I was able to get HMR working with Nitro and Vite. Below is the config settings @rellafella posted, modified to match what has worked for me:

`vite.config.js`
```diff
import vue from '@vitejs/plugin-vue';
import ViteRestart from 'vite-plugin-restart';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import path from 'path';

// https://vitejs.dev/config/
export default ({ command }) => ({
  base: command === 'serve' ? '' : '/dist/',
  build: {
    manifest: true,
    outDir: './web/dist',
    rollupOptions: {
      input: {
        app: './src/js/app.js'
      },
      output: {
        sourcemap: true
      }
    }
  },
  plugins: [
    nodeResolve({
      moduleDirectories: [path.resolve('./node_modules')]
    }),
    ViteRestart({
      reload: ['./templates/**/*']
    }),
    vue()
  ],
  publicDir: './src/public',
  resolve: {
    alias: {
      '@': '/src'
    }
  },
  server: {
+    host: '0.0.0.0',
+    hmr: {
+        host: 'liamrella.test', // you could make this an ENV var
+        port: '3000',
+        path: '/'
+    }
  }
});
```

`vite.php`

```diff
<?php

use craft\helpers\App;

return [
    'useDevServer' => App::env('DEV_MODE'),

    'manifestPath' => '@webroot/dist/manifest.json',

    'devServerPublic' => App::env('VITE_DEV_SERVER_PUBLIC'),

    'serverPublic' => App::env('SITE_URL') . '/dist/',

    'errorEntry' => '/src/js/app.js',

    'cacheKeySuffix' => '',

-    'devServerInternal' => App::env('VITE_DEV_SERVER_PUBLIC'),
+    'devServerInternal' => 'http://localhost:3000/',
    'checkDevServer' => true,
];
```

`relevant env vars`

```diff
DEV_MODE=1
SITE_URL=http://liamrella.test
- VITE_DEV_SERVER_PUBLIC=http://localhost:3000/
+ VITE_DEV_SERVER_PUBLIC=http://liamrella.test:3000/
WEB_ROOT_PATH=/app/web (aliased as @webroot)
```

**Comment by khalwat** [comment]
@andrewmenich nice! And this is running Vite inside of Nitro yes?

**Comment by andrewmenich** [comment]
> @andrewmenich nice! And this is running Vite inside of Nitro yes?

Yep! I just updated my original post to clarify.

**Comment by khalwat** [comment]
Fantastic. I'm praying you decide to write a blog on this :)

**Comment by andrewmenich** [comment]
I plan to! I've pinged a few folks on Discord with my findings to see if it works for them. Just trying to avoid the "_but it works on my machine!_" situation.

**Comment by rellafella** [comment]
@andrewmenich I just tested it and it works! Thanks heaps!

**Comment by roberttolton** [comment]
Unfortunately for my setup, despite following what's been said here, is still not working. The only way I could get rid of the CORS error was to put the Vite Server on a subdomain, like so (Otherwise the requests responded with a 502 ERROR):

```
hmr: {
  host: 'vite.roberttolton.test',
  port: '3000',
  path: '/',
},
```

```
VITE_DEV_SERVER_PUBLIC=http://vite.roberttolton.test:3000/
```

This solves the CORS issue, but my requests to `http://vite.roberttolton.test:3000/js/app.ts` are just met with a blank page. The HTTP response is a 200 OK, but no content data is included at all.

Any help would be much appreciated.

**Comment by stuh** [comment]
Thanks @andrewmenich for this, works a treat here when using http. Just wondering if anyone has managed to get it all going on https? I've tried the [vite-plugin-mkcert](https://github.com/liuweiGL/vite-plugin-mkcert) however on 'npm run dev' within nitro, mkcert fails with Permission Denied.

**Comment by ademers** [comment]
I have Vite working as expected in Nitro 2 when running `npm run dev` and `npm run build` from within Nitro (i.e after running `nitro ssh`).

Now I've installed the Critical CSS companion plugin <https://github.com/nystudio107/rollup-plugin-critical> and have it configured as follows in `vite.config.js`:

```js
    critical({
        criticalUrl: 'http://craft-starter.nitro:8080/',
        criticalBase: './web/dist/criticalcss',
        criticalPages: [
            { uri: 'contact', template: 'contact' },
        ],
        criticalConfig: {
        },
    }),
```
When I run `npm run build`, all works as expected except for the generation of my `contact_critical.min.css`. I get this error which appears to be related to Puppeteer. Maybe Puppeteer + Alpine Linux?

```
Error: Failed to launch the browser process! spawn /app/node_modules/rollup-plugin-critical/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/app/node_modules/rollup-plugin-critical/node_modules/puppeteer/lib/Launcher.js:750:14)
    at ChildProcess.<anonymous> (/app/node_modules/rollup-plugin-critical/node_modules/puppeteer/lib/Launcher.js:741:65)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:288) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn /app/node_modules/rollup-plugin-critical/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/app/node_modules/rollup-plugin-critical/node_modules/puppeteer/lib/Launcher.js:750:14)
    at ChildProcess.<anonymous> (/app/node_modules/rollup-plugin-critical/node_modules/puppeteer/lib/Launcher.js:741:65)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Here's some info on running Puppeteer on Alpine: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-on-alpine

Is there something I can do/need to change, or is it Nitro itself? Thanks!

**Comment by kennyheard** [comment]
Hi, @andrewmenich. I was hoping you could clarify something for me if you'd be so kind!

Is the setup described above and in @khalwat's [article](https://nystudio107.com/blog/using-vite-js-next-generation-frontend-tooling-with-craft-cms) supposed to work with the Live Reload functionality? I've been attempting to run Craft CMS, Nitro, and Vite together, and have managed to get it working to a point. I'm able to hit the site in the browser at `http://<project>.nitro` and can see that the asset URLs are correctly being swapped by [craft-plugin-vite](https://github.com/nystudio107/craft-plugin-vite), but when editing any number of the assets or templates, there are no logs in the browser's console and a manual refresh must be done to see the changes. This doesn't seem to align with the example in the article.

Hitting Vite's development server address directly also just results in a blank page. Is that to be expected?

**Comment by acalvino4** [comment]
Following the tips in this thread, I get below error - any ideas why?
```
WebSocket server error:
Error: getaddrinfo ENOTFOUND http://mysite.nitro
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
```

`vite.php`
```
    'useDevServer' => App::env('ENVIRONMENT') === 'dev',
    'manifestPath' => '@webroot/dist/manifest.json',
    'devServerPublic' => App::env('PRIMARY_SITE_URL') . ':3000/',
    'devServerInternal' => 'http://localhost:3000/',
    'serverPublic' => App::env('PRIMARY_SITE_URL') . '/dist/',
    'checkDevServer' => false,
    ...
```

`vite.config.js`
```
import ViteRestart from 'vite-plugin-restart';
import 'dotenv/config';

// https://vitejs.dev/config/
export default ({ command }) => ({
  base: command === 'serve' ? '' : '/dist/',
  build: {
    emptyOutDir: true,
    manifest: true,
    outDir: './web/dist/',
    rollupOptions: {
      input: {
        app: './src/ts/index.ts',
      },
      output: {
        sourcemap: true,
      },
    },
  },
  plugins: [
    ViteRestart({
      restart: [
          './templates/**/*',
      ],
    }),
  ],
  server: {
    host: '0.0.0.0',
    hmr: {
        host: process.env.PRIMARY_SITE_URL,
        port: '3000',
        path: '/',
    },
  },
});
```

**Comment by acalvino4** [comment]
I've been playing around with trying to get this working with https, since it seems that mixed content errors are the only thing holding me back from a working dev server.

it seems that if you have certs, you can just point to them from your `vite.config.js` like so:
```
  server: {
    https: {
      key: fs.readFileSync('path/to/key.pem'),
      cert: fs.readFileSync('path/to/cert.pem'),
    },
  },
```

But we know that nitro already generates certs for the sites it serves ....... so I'm curious if anyone knows where those are stored / if we could just point to them from our vite config rather than using vite-plugin-mkcert which seems to have permissions issues?

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
